export default defineAppConfig({
  ui: {
    icons: {
      light: "i-ph-sun",
      dark: "i-ph-moon",
      arrowDown: "i-ph-caret-down",
      arrowLeft: "i-ph-caret-left",
      arrowRight: "i-ph-caret-right",
      arrowUp: "i-ph-caret-up",

      caution: "i-ph-warning-circle",
      check: "i-ph-check",
      chevronDoubleLeft: "i-ph-caret-double-left",
      chevronDoubleRight: "i-ph-caret-double-right",
      chevronDown: "i-ph-caret-down",
      chevronLeft: "i-ph-caret-left",
      chevronRight: "i-ph-caret-right",
      chevronUp: "i-ph-caret-up",

      close: "i-ph-x",
      copy: "i-ph-copy",
      copyCheck: "i-ph-checks",
      system: "i-ph-desktop",

      ellipsis: "i-ph-dots-three",
      error: "i-ph-x-circle",
      external: "i-ph-arrow-up-right",
      eye: "i-ph-eye",
      eyeOff: "i-ph-eye-slash",
      file: "i-ph-file",
      folder: "i-ph-folder",
      folderOpen: "i-ph-folder-open",
      hash: "i-ph-hash",
      info: "i-ph-info",
      loading: "i-ph-spinner-gap",
      menu: "i-ph-list",
      minus: "i-ph-minus",
      plus: "i-ph-plus",
      reload: "i-ph-arrow-clockwise",
      search: "i-ph-magnifying-glass",
      stop: "i-ph-stop",
      success: "i-ph-check-circle",
      tip: "i-ph-lightbulb",
      upload: "i-ph-upload",
      warning: "i-ph-warning",
    },

    // colors: {
    //   primary: "primary",
    // },
  },
});
